version: '3.3'
services:
  mongo:
    image: mongo
    env_file:
      - ./env/mongo.env
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    volumes:
      - 'mongo-data:/data/db'
  mongo-express:
    image: mongo-express
    env_file:
      - ./env/mongo-express.env
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  backend:
    build: ./backend
    depends_on:
      - mongo
    env_file:
      - ./env/app.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/src/:/app/src
    command: npm run dev
volumes:
  mongo-data:
