version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
          # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
          # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
          MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        image: mongo
        volumes:
          - './data:/data/db'
    mongo-express:
        image: mongo-express
        environment:
          ME_CONFIG_MONGODB_SERVER: mongo
          ME_CONFIG_MONGODB_PORT: 27017
          # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
          # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
          # ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
          # ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
          # ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
          # ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}            
          ME_CONFIG_BASICAUTH: false
          ME_CONFIG_MONGODB_ENABLE_ADMIN: false
          # ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        depends_on:
            - mongo
        ports:
          - "8081:8081"